'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class home
    
    '''<summary>
    '''uc_header control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uc_header As Global.MDS.uc_header
    
    '''<summary>
    '''ul_approve control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ul_approve As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''ul_supir control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ul_supir As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''ul_cc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ul_cc As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''ul_info control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ul_info As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''ul_tmc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ul_tmc As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''ul_ultah control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ul_ultah As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''uc_footer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uc_footer As Global.MDS.uc_footer
End Class
