'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class mds_lap_sj
    
    '''<summary>
    '''uc_header control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uc_header As Global.MDS.uc_header
    
    '''<summary>
    '''s_date control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents s_date As Global.DevExpress.Web.ASPxDateEdit
    
    '''<summary>
    '''e_date control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents e_date As Global.DevExpress.Web.ASPxDateEdit
    
    '''<summary>
    '''bt_refresh control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bt_refresh As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''ASPxPivotGrid1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxPivotGrid1 As Global.DevExpress.Web.ASPxPivotGrid.ASPxPivotGrid
    
    '''<summary>
    '''fieldsupir control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fieldsupir As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField
    
    '''<summary>
    '''fieldsumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fieldsumber As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField
    
    '''<summary>
    '''fieldqty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fieldqty As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField
    
    '''<summary>
    '''fieldnosj control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fieldnosj As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField
    
    '''<summary>
    '''fieldtgl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fieldtgl As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField
    
    '''<summary>
    '''fieldtrayek control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fieldtrayek As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField
    
    '''<summary>
    '''fieldasal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fieldasal As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField
    
    '''<summary>
    '''fieldtujuan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fieldtujuan As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField
    
    '''<summary>
    '''fieldcust control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fieldcust As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField
    
    '''<summary>
    '''fieldnopol control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fieldnopol As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField
    
    '''<summary>
    '''fieldharga control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fieldharga As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField
    
    '''<summary>
    '''uc_footer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uc_footer As Global.MDS.uc_footer
End Class
