'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class mds_data_driver
    
    '''<summary>
    '''uc_header control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uc_header As Global.MDS.uc_header
    
    '''<summary>
    '''img_supir control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents img_supir As Global.DevExpress.Web.ASPxImage
    
    '''<summary>
    '''tx_nama control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tx_nama As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''tx_tgl_lhr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tx_tgl_lhr As Global.DevExpress.Web.ASPxDateEdit
    
    '''<summary>
    '''cb_jk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cb_jk As Global.DevExpress.Web.ASPxComboBox
    
    '''<summary>
    '''tx_no_ktp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tx_no_ktp As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''tx_phone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tx_phone As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''tx_alamat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tx_alamat As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''tx_pendidikan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tx_pendidikan As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''tx_lama_kerja control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tx_lama_kerja As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''tx_jns_sim control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tx_jns_sim As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''tx_no_sim control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tx_no_sim As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''tx_no_rek control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tx_no_rek As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''cb_bank control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cb_bank As Global.DevExpress.Web.ASPxComboBox
    
    '''<summary>
    '''tx_tgl_bergabung control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tx_tgl_bergabung As Global.DevExpress.Web.ASPxDateEdit
    
    '''<summary>
    '''tx_no_bpjs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tx_no_bpjs As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''uc_footer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uc_footer As Global.MDS.uc_footer
End Class
