'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class uc_chart

    '''<summary>
    '''a_bar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents a_bar As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''a_line control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents a_line As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''a_pai control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents a_pai As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''a_turner control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents a_turner As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''a_radar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents a_radar As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''a_donut control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents a_donut As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''a_spline control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents a_spline As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''a_label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents a_label As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''a_legend control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents a_legend As Global.System.Web.UI.HtmlControls.HtmlAnchor
End Class
