'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class uc_header

    '''<summary>
    '''list_menu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Public WithEvents list_menu As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''a_filter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Public WithEvents a_filter As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''a_column control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Public WithEvents a_column As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''a_field control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Public WithEvents a_field As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''a_export control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Public WithEvents a_export As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''bt_pdf control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Public WithEvents bt_pdf As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''bt_excel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Public WithEvents bt_excel As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''pivot_export control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Public WithEvents pivot_export As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''pivot_pdf control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Public WithEvents pivot_pdf As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''pivot_excel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Public WithEvents pivot_excel As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''lb_isi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Public WithEvents lb_isi As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''filter_cb1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Public WithEvents filter_cb1 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''filter_tx1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Public WithEvents filter_tx1 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''filter_cb2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Public WithEvents filter_cb2 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''filter_tx2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Public WithEvents filter_tx2 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''filter_cb3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Public WithEvents filter_cb3 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''filter_de1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Public WithEvents filter_de1 As Global.DevExpress.Web.ASPxDateEdit

    '''<summary>
    '''filter_de2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Public WithEvents filter_de2 As Global.DevExpress.Web.ASPxDateEdit

    '''<summary>
    '''ASPxGridViewExporter1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Public WithEvents ASPxGridViewExporter1 As Global.DevExpress.Web.ASPxGridViewExporter

    '''<summary>
    '''ASPxPivotGridExporter1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Public WithEvents ASPxPivotGridExporter1 As Global.DevExpress.Web.ASPxPivotGrid.ASPxPivotGridExporter

    '''<summary>
    '''div_max control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Public WithEvents div_max As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''div_search control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Public WithEvents div_search As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''tx_search control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Public WithEvents tx_search As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''bt_search control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Public WithEvents bt_search As Global.System.Web.UI.HtmlControls.HtmlButton
End Class
