'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class uc_menu
    
    '''<summary>
    '''a_autho_grp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents a_autho_grp As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''a_autho_user control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents a_autho_user As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''a_mst_apd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents a_mst_apd As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''a_mst_ba control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents a_mst_ba As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''a_mst_izin_jns control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents a_mst_izin_jns As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''a_mst_kateg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents a_mst_kateg As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''a_mst_limit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents a_mst_limit As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''a_mst_rtt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents a_mst_rtt As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''a_mst_templ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents a_mst_templ As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''a_mst_training control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents a_mst_training As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''a_rec_applicant control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents a_rec_applicant As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''a_trs_acc_inc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents a_trs_acc_inc As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''a_trs_ba control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents a_trs_ba As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''a_driver_act control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents a_driver_act As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''a_driver_inact control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents a_driver_inact As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''a_trs_training control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents a_trs_training As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''a_trs_izin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents a_trs_izin As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''a_trs_mcu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents a_trs_mcu As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''a_trs_apd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents a_trs_apd As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''a_skontrak control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents a_skontrak As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''a_trs_tegur control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents a_trs_tegur As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''a_mon_supir control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents a_mon_supir As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''a_mon_pass control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents a_mon_pass As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''a_lap_apd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents a_lap_apd As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''a_lap_accident control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents a_lap_accident As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''a_lap_ba control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents a_lap_ba As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''a_lap_supir control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents a_lap_supir As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''a_lap_izin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents a_lap_izin As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''a_lap_mcu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents a_lap_mcu As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''a_lap_sj control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents a_lap_sj As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''a_lap_teg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents a_lap_teg As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''a_lap_training control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents a_lap_training As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''a_help_userguide control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents a_help_userguide As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''a_help_flow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents a_help_flow As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''a_help_uat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents a_help_uat As Global.System.Web.UI.HtmlControls.HtmlGenericControl
End Class
